name: gasosa_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase / Auth
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1

  # Navegação
  go_router: ^16.2.0

  # Persistência local
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5

  # DI
  get_it: ^8.2.0
  path: ^1.9.1
  google_fonts: ^6.3.0
  dartz: ^0.10.1
  mockito: ^5.5.0
  validatorless: ^1.2.4
  top_snackbar_flutter: ^3.3.0
  loading_animation_widget: ^1.3.0
  mocktail: ^1.0.4
  flutter_slidable: ^4.0.1
  image_picker: ^1.2.0
  uuid: ^4.5.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 👉 Flavor automation
  flutter_flavorizr: ^2.4.1
  build_runner: ^2.7.0
  drift_dev: ^2.28.1
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
# ---------- FLAVORIZR CONFIG ----------
flavorizr:
  app:
    android:
      flavorDimensions: "env"
    ios: {}

  flavors:
    dev:
      app:
        name: "Gasosa [Dev]"
      android:
        applicationId: "dev.etherealcodes.gasosaapp.dev"
      ios:
        bundleId: "dev.etherealcodes.gasosaapp.dev"
      firebase:
        # Coloque estes arquivos nos caminhos abaixo:
        android: "firebase/dev/google-services.json"
        ios: "firebase/dev/GoogleService-Info.plist"
      icons:
        android: "assets/icons/dev.png"   # opcional
        ios: "assets/icons/dev.png"       # opcional

    prod:
      app:
        name: "Gasosa"
      android:
        applicationId: "dev.etherealcodes.gasosaapp"
      ios:
        bundleId: "dev.etherealcodes.gasosaapp"
      firebase:
        # Trocar para prod futuramente
        android: "firebase/dev/google-services.json"
        ios: "firebase/dev/GoogleService-Info.plist"
      icons:
        android: "assets/icons/prod.png"  # opcional
        ios: "assets/icons/prod.png"      # opcional
# --------------------------------------
