// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ttWgTlt0Bsa0hNZGE5jt3sVg8h_MWAE',
    appId: '1:155550412551:android:764259cefe63e9add01fa2',
    messagingSenderId: '155550412551',
    projectId: 'etharch-gasosa-app-dev',
    storageBucket: 'etharch-gasosa-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZvM8j_FeMDwLOHcehuLVVOlsqUB5YPeA',
    appId: '1:155550412551:ios:064250077e2c61a2d01fa2',
    messagingSenderId: '155550412551',
    projectId: 'etharch-gasosa-app-dev',
    storageBucket: 'etharch-gasosa-app-dev.firebasestorage.app',
    androidClientId: '155550412551-1gord8guekvu9p3qcrdmmkcb6ip6jhtd.apps.googleusercontent.com',
    iosClientId: '155550412551-a6e96q636maf4ail7m5b6f3jd5nhg8oi.apps.googleusercontent.com',
    iosBundleId: 'dev.etherealcodes.gasosaapp.dev',
  );
}
